repos:

-   repo: https://github.com/ambv/black

    rev: 19.3b0

    hooks:

    - id: black

      language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy

    rev: v0.740

    hooks:

    - id: mypy

    args: [--no-warn-unused-ignores]
